language: cpp

dist: trusty
sudo: required

git:
  depth: 10

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
      dist: trusty

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./util/osx/prepare.sh & ./util/osx/prepare.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./util/ubuntu/prepare.sh & sudo ./util/ubuntu/prepare.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./util/osx/build.sh & ./util/osx/build.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./util/ubuntu/build.sh & ./util/ubuntu/build.sh; fi

deploy:
  - provider: releases
    api_key:
      secure: "GtsMSa6lXB7BpMu7ayfPQXYGoiVeyo6wO3gG3OLjFvucAjCGK4lRb7olB+lkPXvIXxXFDo8sZvrr5KxV3pZjO0sWlAnh3GuoKViWJfk3DHKzm6Wxwuy/tt7MUrhVPIrJZSYUskzHQIPigbu3h+gDJX/M6WUbxcArG0YR4r07sQK375FhK76PL9ctUonUvFZQHxeBz0aAtphSJs0T6KF+P1mYs4CbhDG8zqdBFThFARLdKq5mp82D0508ZGWQKMZxqvEajnfpiYOMbI3kYLK1swUuyZG+96/6C2lU+4SS77Bof6lVoseTBSu4cTXF4ESVniI4NOAeEi3scJUbzdu1VKWIYC0eoyDTe6HLJ0vSz2VQ+Aao7UApmqhkI35eSDt2aSZsTw9Vu+BT37WNmCPA0JApgdacomNkuiqQHhDQUPA9YHVkRHyf6mkBYJJwmyQPVRLFGk7jmWR/1Qwxa3QpwMMAFHitQ1WYMHR6P7/OUCUAp7Jo8xgQpiH4djjy76YJ6Etf5vuyWtM8PksP/cZthuaBrRdHvnhiIpF41PSVIcVO+u1co8SWMcv94P0dZM5DF8pu7eesNYpLGgpG87odxjuFl/H/VzH3PRMb7J4r8rE9nJdUrH+gUEACGADm21w9F60H0c/Mcgw7dkJMhX4ZpjPwyn74KbisyEAif2cA2Fg="
    file_glob: true
    file: "QtcUtilities-*.tar.gz"
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    on_success: change
    on_failure: change
